### ISSUE TITLE
Change arguments in calculation of transform between PCs

### ISSUE THREAD

**Issue by Bardo91** [Bardo91/StereoTests#7]
We use the transformation guess in this function, so it is not as general for any input as we like, since this general guess is in regards to the entire map (mCloud).

Possible solution: Add a new argument (initial guess) with identity as default.

**Comment by dzoberti** [comment]
Fixed the function to receive 2 optional input arguments. One is the initial guess, which is otherwise an identity and the other one is the aligned point cloud. This way there is no need to transform the cloud with the returned transformation, if that is required. This optional parameter represents a possible problem for compilation in g++
